# Generated by Django 5.0.6 on 2024-06-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.AddField(
            model_name='contato',
            name='primeiro_nome',
            field=models.CharField(default='', max_length=100, verbose_name='Primeiro nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='segundo_nome',
            field=models.CharField(default=' ', max_length=100, verbose_name='Segundo nome'),
            preserve_default=False,
        ),
    ]
