# Generated by Django 5.0.6 on 2024-06-24 02:26

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_contato_nome_contato_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=stdimage.models.StdImageField(default=' ', force_min_size=False, upload_to='rostos_contatos', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
