# Generated by Django 5.0.6 on 2024-06-24 14:30

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contato_imagem_alter_contato_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='rostos_contatos', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='primeiro_nome',
            field=models.CharField(max_length=100, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Segundo nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
